version: 0.2

env:
  shell: bash

batch:
  fast-fail: false
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      golang: 1.18

  build:
    on-failure: ABORT
    commands:
      - echo "start build"
      - GOOS=linux GOARCH=amd64 go build -o handler main.go
      - zip function.zip handler
      - ls -al
      - echo "finish build"
